version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/test/deltares_testbench/pip"
      - "/test/deltares_testbench"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Amsterdam"
